Version 0.1
openscilab/dmeta pull request #30
Opened 2024-06-18 11:16 UTC by AHReccese

#### Reference Issues/PRs

#### What does this implement/fix? Explain your changes.

#### Any other comments?

2024-06-18 22:04 UTC, sepandhaghighi requested changes
@AHReccese 

Please make sure to update the email address in the `README.md` file.

2024-06-19 00:10 UTC, sadrasabouri approved these changes

2024-06-19 08:33 UTC, AHReccese commented
> @AHReccese
> 
> Please make sure to update the email address in the `README.md` file.

Done.

2024-06-19 10:51 UTC, sepandhaghighi approved these changes
🚀

2024-06-19 11:01 UTC, merged