Version 0.2
openscilab/dmeta pull request #37
Opened 2024-08-12 01:52 UTC by AHReccese

#### Reference Issues/PRs
#12 #13 #21 
#### What does this implement/fix? Explain your changes.
Version 0.2 release PR
#### Any other comments?

2024-08-12 02:49 UTC, sadrasabouri requested changes
minor change request.

2024-08-12 02:49 UTC, sadrasabouri commented on CHANGELOG.md
> +[0.2]: https://github.com/openscilab/dmeta/compare/v0.1...v0.2
The order should be new to old:
```
[Unreleased]: ...
[0.2]: ...
[0.1]: ...
```

2024-08-12 02:55 UTC, AHReccese commented
Guys, after reviewing it, please do not merge it.

2024-08-12 02:56 UTC, sadrasabouri approved these changes

2024-08-12 02:57 UTC, AHReccese commented
I may have a very minor PR (not sure, reviewing every single detail)

2024-08-13 15:27 UTC, sadrasabouri commented
Remember to update release with current `dev`.

2024-08-13 16:41 UTC, AHReccese commented
> Remember to update release with current `dev`.
@sadrasabouri 
Is it necessary? I think there is no conflict here.

2024-08-13 16:43 UTC, sadrasabouri commented
> > Remember to update release with current `dev`.
> > @sadrasabouri
> Is it necessary? I think there is no conflict here.

You can try. But I always wonder merging such a PRs. The `dev` that `release` originated from is not the same `dev` it's merging to.

2024-08-13 22:54 UTC, sepandhaghighi approved these changes
🚀

2024-08-13 23:23 UTC, merged